{{- if .Values.hpa.autoscaling.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.deploy.name }}-hpa
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.deploy.name }}-deployment
  minReplicas: {{ .Values.hpa.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.hpa.autoscaling.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.hpa.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}